' @startuml
' [*] --> State1
' State1 --> [*]
' State1 : this is a string
' State1 : this is another string

' State1 -> State2
' State2 --> [*]
' @enduml
' run code ALT+d, state1 = red, state2 = green, state3 = yellow

@startuml
State:red #red -d-> State:green : go
State:red -> State:red : Stop

State:green #green -> State:green : go
State:green -down-> State:yellow : stop

State:yellow #yellow -right-> State:yellow : go
State:yellow -> State:yellow : stop
State:yellow -> State:red : Timeout

@enduml